### ISSUE TITLE
console log

### ISSUE THREAD

**Issue by bp2468** [M74JJI/whatsapp_fe#2]
Uncaught TypeError: Cannot read properties of undefined (reading 'split')

**Comment by bp2468** [comment]
ncaught TypeError: Cannot read properties of undefined (reading 'split')
    at ./src/App.js (App.js:16:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/index.js (userSlice.js:97:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at startup:7:1
    at startup:7:1
